---
title: "Replication of Revealing Hidden Gender Biases in Competence Impressions of Faces by Oh et al. (2019, Psychological Science)"
author: "Candice Kim (candicekim@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

##Introduction

For this project, I seek to replicate the findings of Experiment 3 of the study conducted by Oh et al. (2019) titled "Revealing Hidden Gender Biases in Competence Impressions of Faces." This study overall sought to identify the components of competence stereotype using data-driven computational models. For Experiment 3, the authors tested whether gender-related facial cues were used to judge competence. They presented participants with faces that varied on perceived competence and asked them to categorize them as male or female. THe authors found that faces manipulated to appear competent but not attractive were more likely to be classified as male, suggesting that gender bias influences competence impressions. I am interested in replicating this study, and particularly this experiment, because of my research interest in gender equity in medicine. Prior research has shown that leadership in academic medicine and specific medical specialties such as surgery are overwhelmingly male dominated. Better understanding the role of gender bias on critical factors such as perceived competence, which influences hiring decisions, promotions, and program acceptance rates, can provide insight on current gender gaps in medicine.

This reproduction study will be conducted using Amazon Mechanical Turk (MTurk) to recruit participants. The original study included 30 participants, accounting for test-retest reliability of greater than 0. The authors used face images computationally manipulated using both the competence model and the difference model to generate a pool of 350 face-image stimuli (2 models x 25 identities x 7 manipulation levels). For each face-image stimulus, participants were asked to make a forced choice of male or female. Two version of the study were created: (1) 88 competence-model faces + 87 difference-model faces and (2) 87 competence-model faces + 88 difference-model faces. Each version included unique image stimuli with no overlap of images. The 175 images for each version were presented to the participant, who was then asked to respond to the question "What is the gender of this person?" with two options male or female. To assess intrarater reliability, 25 trials from the first 175 trials were randomly repeated to bring the total of trials to 200 for each participant. Responses of participants who had a test-retest reliability less than or equal to 0 were excluded. I believe the major challenge to reproducing this study will be generating the face-image stimuli since I am not familiar with the program the authors used to create the images. Perhaps I can use the same images the authors used in their study, but I am not sure if this would be considered sufficient for this replication project. Additionally, I have not used Amazon MTurk before and have limited coding experience. As such, I am not sure how difficult it will be to create the interface needed for the 200 trials (the last 25 of which are random repeats from the first 175) and whether my coding experience will be sufficient. One potential concern I had was being able to recruit enough participants on MTurk. However, for this study, the authors included 30 participants, which seems like an attainable number.

[Repository](https://github.com/candicejkim/oh2019/)

[Original Paper](https://github.com/candicejkim/oh2019/blob/master/original_paper/Oh_etal_2019.pdf)

##Methods

###Power Analysis

The original effect size was eta-squared = 0.88 (p < .001) with F = 464.32 for a repeated measures ANOVA test. The authors' power analysis was conducted using G*Power 3.1.9, which calculated that a "sample size of at least 26 participants would afford 95% power to detect a small to medium effect (f = .25) of the main effects of manipulation level and model type, as well as the interaction between the two."

Using similar parameters, as described above, my power analysis using G*Power calculated that I would need a sample size of 28 participants to achieve 95% power, 90% power, and 85% power (sample size did not change).

###Planned Sample

The original study included 30 participants with an intrarater reliability score greater than 0 (see procedure section for more details). The same sample size will be planned for this replication report. The original study ended up including 31 participants total because 1 participant had an intrarater reliability score of 0.

For this replication study, ideally enough participants would be recruited - and the study will remain open - until 30 participants with an intrarater reliability score greater than 0 participate. However, given feasibility of cost, I will instead set the total number of participants as 30, providing flexibility of up to 2 participants to be excluded (if they have an intrarater reliability score of 0) and still achieve the desired power as described above.

The original study did not specify known demographics or preselection rules. For this replication study, the typical MTurk qualifications (located in US, HIT approval rate greater than 97%, and greater than 5000 number of HITs approved) will be used.

###Materials

"We used both the face images manipulated by the competence model and the face images manipulated by the difference model. This created a combined pool of 350 face-image stimuli (2 models × 25 identities × 7 manipulation levels)." The same materials from the original study, quoted above, will be followed for this replication study.

[Paradigm](https://stanforduniversity.qualtrics.com/jfe/form/SV_2mhyDSzzzr2q2Il)

###Procedure	

"Participants were asked to make a forced choice of perceived gender for each face. All participants were exposed to faces from both the competence and difference models. Two versions of the study with the same length were created: Half of the participants were presented with 88 competence-model faces and 87 difference-model faces, whereas the other half were presented with 87 competence-model faces and 88 difference-model faces. There was no overlap in the face images between the two versions of the study.

The 175 chosen stimuli were presented in random order to each participant. For each stimulus, the question asked was “What is the gender of this person?” presented with two options: male or female. Left and right arrow keys were used to indicate one or the other gender, and the gender–key mapping was counterbalanced. Before the experiment began, each participant was told to rely on gut instinct, not to spend too much time on each face, and that there were no right or wrong answers. Participants were given unlimited time.

To assess intrarater reliability, we added 25 repeated trials randomly chosen from the first 175 trials in each study, bringing the total number of trials to 200. As we did in the previous experiments, we excluded the responses of participants with test-retest reliability less than or equal to 0: 1 participant. We recruited an additional participant so that we had 30 participants with test-retest reliability greater than 0." The same procedure from the original study, quoted above, will be followed for this replication study.

###Analysis Plan

In this study, participants are asked to assign binary gender - male or female - to computer-generated face images that have been manipulated either according to the competence model or the difference model. Participants are excluded if their intrarater reliability score is 0 (see procedure section above).

The first analysis the authors conducted was a t-test to determine whether the proportion of "male" responses to all faces averaged across participants was significantly different from 0.5.

The second analysis they conducted involved plotting the mean proportion of "male" responses as a function of the level of the difference-model manipulation and the competence-model manipulation. The graph was fitted with a sigmoid function for the response averaged across participants with error bars denoting standard errors.

The third analysis they conducted was a "7 (manipulation level) × 2 (model type) repeated measures analysis of variance on the proportion of 'male' responses for each face." The most relevant test for replication was the repeated measures ANOVA on the proportion of "male" responses for each face, comparing when faces were manipulated by the competence model versus the difference model.

**Clarify key analysis of interest here**  The key analysis of interest is the second analysis described above in which the mean proportion of "male" responses will be plotted as a function of the difference and competence-model manipulations. A sigmoid function will be fitted to the resulting plot with error bars indicating standard errors. There will be a single plot generated with the responses averaged across participants. This graph will essentially be a replication of the original paper's Figure 4, which was the key figure for the experiment being replicated.

###Differences from Original Study

The procedure, analysis plan, and setting of MTurk will exactly follow the original study. A difference, however, will likely be the participants' demographics. The original study did not specify any particular restrictions for excluding MTurk workers from participating. As such, this replication study will follow the standard MTurk qualifications (located in the US, HIT approval rate greater than 97%, and greater than 5000 HITs approved). Other than these qualifications, the study will be open to any MTurk workers who agree to participate. In the original study, "thirty-one MTurk workers (22 men, 9 women; age: M = 36.32 years, range = 20–58) participated." One of these MTurk workers was excluded from analysis because their intrarater reliability score was equal to 0 (refer to procedure section). When recruiting participants for this replication report, the same demographics in terms of age range and gender breakdown may not be the same. As the original study cited, prior research has shown that "people evaluate men as more competent and more confident than women, on average" and that the "association between men and competence, confidence, and semanitically similar traits (e.g. independence, inventiveness) are held across diverse cultures." As such, although  the  demographics of MTurk workers will likely not be precisely the same for this replication study, it is anticipated that this difference will not drastically influence the outcomes of the study.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results

### Data preparation

Data preparation following the analysis plan.

### Confirmatory analysis

```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions
library(readr)
library(tidyverse)
library(ggplot2)
library(reshape)
library(dplyr)
library(ggpubr)

####Import data
d <- read_csv("Oh2019_PilotA.csv")

#### Demographics
view(d)
d_demo = d %>% 
  select(-c("StartDate", "EndDate", "Status", "Progress", "Duration (in seconds)", "Finished", "RecordedDate", "ResponseId", "DistributionChannel", "UserLanguage", "mTurk"))

d_demo <- d_demo[-c(1, 2), ] # remove unnecessary rows
view(d_demo)

# find number of male and female participants
n_participants = 3 # number of participants, n=3 for Trial A
n_male = 0
n_female = 0
for (i in 1:n_participants) { # this for loop recodes male/female to 1/0
  if (d_demo[i, 702] == "Male") {
    n_male = n_male + 1
  } else {
    n_female = n_female + 1
  }
}
print(n_male) # number of male participants
print(n_female) # number of female participants

# calculate range of age (Q29)
age_range = range(d_demo$Q29) # find min and max age values
print(age_range) # print range

# calculate mean of age (Q29)
age_df <- data.frame(matrix(NA, nrow = n_participants, ncol = 1))
for (i in 1:n_participants) { # this for loop recodes male/female to 1/0
  age_df[i,1] = d_demo[i,701]
}

mean(as.numeric(age_df[,1])) # convert strings into numbers, then report mean

#### Data exclusion / filtering
d_exclusion = d %>% 
  select(-c("StartDate", "EndDate", "Status", "Progress", "Duration (in seconds)", "Finished", "RecordedDate", "ResponseId", "DistributionChannel", "UserLanguage", "mTurk", "Q29", "Q30"))

d_exclusion <- d_exclusion[-c(1, 2), ] # remove unnecessary rows

t_d_exclusion <- as.data.frame(t(d_exclusion)) # transpose columns & rows (make data long instead of wide)

for (i in 1:n_participants) { # this for loop recodes male/female to 1/0
  t_d_exclusion[,i] <- ifelse(t_d_exclusion[,i] == "Male", 1, ifelse(t_d_exclusion[,i] == "Female", 0, 2))
}

# compare repeat questions check whether intra-rater reliability (Pearson's correlation between 25 repeat questions) is equal to 0, if so will need to exclude
total_q= 175 # questions are in rows, total # of questions in each version

for(j in 1:n_participants) {
  #print("working on")
  #print(j)
  
  is_ver1 = !is.na(t_d_exclusion[1,j])
  k=1
  temp_frame <- data.frame(matrix(NA, nrow = 25, ncol = 2))
  for(i in 1:total_q) {
    if (is_ver1) {
      init_q = i
      compare_q = i + total_q
    } else {
      init_q = i + 2*total_q
      compare_q = i + 3*total_q
    }
    if(!is.na(t_d_exclusion[compare_q, j])) {
      temp_frame[k,1] = t_d_exclusion[init_q, j]
      temp_frame[k,2] = t_d_exclusion[compare_q, j]
      #print(k)
      k = k + 1
    }
  }
  coeff = cor(temp_frame[,1], temp_frame[,2], method = "pearson")
  print(coeff)
  
  if(coeff == 0) {
    print(j)
  } else {print("acceptable")}
}

#### Prepare data for analysis - create columns etc.
filtered_d = d %>% 
  select(-c("StartDate", "EndDate", "Status", "Progress", "Duration (in seconds)", "Finished", "RecordedDate", "ResponseId", "DistributionChannel", "UserLanguage", "Q29", "Q30", "mTurk"),
  -contains("Q")) # remove unnecessary columns
filtered_d <- filtered_d[-c(1, 2), ] # remove unnecessary rows
t_filtered_d <- as.data.frame(t(filtered_d)) # transpose columns & rows (make data long instead of wide)

n_participants = 3 # number of participants
for (i in 1:n_participants) { # this for loop recodes male/female to 1/0
  t_filtered_d[,i] <- ifelse(t_filtered_d[,i] == "Male", 1, ifelse(t_filtered_d[,i] == "Female", 0, 2))
}

t_filtered_d$image_name <- rownames(t_filtered_d) # copy row names into a column
t_filtered_d = t_filtered_d %>% 
  separate(image_name, into = c("condition", "standard_dev")) # create columns for condition (competence & difference models) and standard deviation (1-7 for image manipulation)

t_filtered_d = t_filtered_d %>%
  mutate(image_id = condition)

n=n_participants
t_filtered_d[,n+1] <- ifelse(t_filtered_d[,n+1] == "Comp01", "comp", ifelse(t_filtered_d[,n+1] == "Comp02", "comp",                                 ifelse(t_filtered_d[,n+1] == "Comp03", "comp",                                 ifelse(t_filtered_d[,n+1] == "Comp04", "comp",
ifelse(t_filtered_d[,n+1] == "Comp05", "comp",
ifelse(t_filtered_d[,n+1] == "Comp06", "comp",
ifelse(t_filtered_d[,n+1] == "Comp07", "comp",
ifelse(t_filtered_d[,n+1] == "Comp08", "comp",
ifelse(t_filtered_d[,n+1] == "Comp09", "comp",
ifelse(t_filtered_d[,n+1] == "Comp10", "comp",
ifelse(t_filtered_d[,n+1] == "Comp11", "comp",
ifelse(t_filtered_d[,n+1] == "Comp12", "comp",
ifelse(t_filtered_d[,n+1] == "Comp13", "comp",
ifelse(t_filtered_d[,n+1] == "Comp14", "comp",
ifelse(t_filtered_d[,n+1] == "Comp15", "comp",
ifelse(t_filtered_d[,n+1] == "Comp16", "comp",                                 ifelse(t_filtered_d[,n+1] == "Comp17", "comp",                                 ifelse(t_filtered_d[,n+1] == "Comp18", "comp",
ifelse(t_filtered_d[,n+1] == "Comp19", "comp",
ifelse(t_filtered_d[,n+1] == "Comp20", "comp",
ifelse(t_filtered_d[,n+1] == "Comp21", "comp",
ifelse(t_filtered_d[,n+1] == "Comp22", "comp",
ifelse(t_filtered_d[,n+1] == "Comp23", "comp",
ifelse(t_filtered_d[,n+1] == "Comp24", "comp",
ifelse(t_filtered_d[,n+1] == "Comp25", "comp",
"diff"))))))))))))))))))))))))) # rename condition variable to be comp/diff

                                                                
t_filtered_d[,n+2] <- ifelse(t_filtered_d[,n+2] == 1, -3, ifelse(t_filtered_d[,n+2] == 2, -2, ifelse(t_filtered_d[,n+2] == 3, -1, ifelse(t_filtered_d[,n+2] == 4, 0, ifelse(t_filtered_d[,n+2] == 5, 1, ifelse(t_filtered_d[,n+2] == 6, 2, ifelse(t_filtered_d[,n+2] == 7, 3, 4))))))) # recode standard deviation values to be -3 to 3

# create separate dataframes by condition and standard deviation
## competent
d_comp_minus3 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == -3)
d_comp_minus2 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == -2)
d_comp_minus1 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == -1)
d_comp_0 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == 0)
d_comp_1 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == 1)
d_comp_2 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == 2)
d_comp_3 = t_filtered_d %>%
  filter(condition == "comp", standard_dev == 3)
## difference
d_diff_minus3 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == -3)
d_diff_minus2 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == -2)
d_diff_minus1 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == -1)
d_diff_0 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == 0)
d_diff_1 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == 1)
d_diff_2 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == 2)
d_diff_3 = t_filtered_d %>%
  filter(condition == "diff", standard_dev == 3)

# create dataframe to hold values for proportion male responses
standard_dev <- c(-3, -2, -1, 0, 1, 2, 3)
prop_male <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
standard_error <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
condition <- c("competence", "competence", "competence", "competence", "competence", "competence", "competence", "difference", "difference", "difference", "difference", "difference", "difference", "difference")
prop_male <- data.frame(standard_dev, prop_male, standard_error, condition)

# input values into dataframe for proportions of male responses by standard deviation and condition

d_comp_minus3 = d_comp_minus3 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[1,2] = mean(as.matrix(d_comp_minus3), na.rm=T)
n_comp_minus3 = length(d_comp_minus3[!is.na(d_comp_minus3)])
prop_male[1,3] = sd(as.matrix(d_comp_minus3), na.rm=T)/sqrt(n_comp_minus3)

d_comp_minus2 = d_comp_minus2 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[2,2] = mean(as.matrix(d_comp_minus2), na.rm=T)
n_comp_minus2 = length(d_comp_minus2[!is.na(d_comp_minus2)])
prop_male[2,3] = sd(as.matrix(d_comp_minus2), na.rm=T)/sqrt(n_comp_minus2)

d_comp_minus1 = d_comp_minus1 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[3,2] = mean(as.matrix(d_comp_minus1), na.rm=T)
n_comp_minus1 = length(d_comp_minus1[!is.na(d_comp_minus1)])
prop_male[3,3] = sd(as.matrix(d_comp_minus1), na.rm=T)/sqrt(n_comp_minus1)

d_comp_0 = d_comp_0 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[4,2] = mean(as.matrix(d_comp_0), na.rm=T)
n_comp_0 = length(d_comp_0[!is.na(d_comp_0)])
prop_male[4,3] = sd(as.matrix(d_comp_0), na.rm=T)/sqrt(n_comp_0)

d_comp_1 = d_comp_1 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[5,2] = mean(as.matrix(d_comp_1), na.rm=T)
n_comp_1 = length(d_comp_1[!is.na(d_comp_1)])
prop_male[5,3] = sd(as.matrix(d_comp_1), na.rm=T)/sqrt(n_comp_1)

d_comp_2 = d_comp_2 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[6,2] = mean(as.matrix(d_comp_2), na.rm=T)
n_comp_2 = length(d_comp_2[!is.na(d_comp_2)])
prop_male[6,3] = sd(as.matrix(d_comp_2), na.rm=T)/sqrt(n_comp_2)

d_comp_3 = d_comp_3 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[7,2] = mean(as.matrix(d_comp_3), na.rm=T)
n_comp_3 = length(d_comp_3[!is.na(d_comp_3)])
prop_male[7,3] = sd(as.matrix(d_comp_3), na.rm=T)/sqrt(n_comp_3)

##difference
d_diff_minus3 = d_diff_minus3 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[8,2] = mean(as.matrix(d_diff_minus3), na.rm=T)
n_diff_minus3 = length(d_diff_minus3[!is.na(d_diff_minus3)])
prop_male[8,3] = sd(as.matrix(d_diff_minus3), na.rm=T)/sqrt(n_diff_minus3)

d_diff_minus2 = d_diff_minus2 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[9,2] = mean(as.matrix(d_diff_minus2), na.rm=T)
n_diff_minus2 = length(d_diff_minus2[!is.na(d_diff_minus2)])
prop_male[9,3] = sd(as.matrix(d_diff_minus2), na.rm=T)/sqrt(n_diff_minus2)

d_diff_minus1 = d_diff_minus1 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[10,2] = mean(as.matrix(d_diff_minus1), na.rm=T)
n_diff_minus1 = length(d_diff_minus1[!is.na(d_diff_minus1)])
prop_male[10,3] = sd(as.matrix(d_diff_minus1), na.rm=T)/sqrt(n_diff_minus1)

d_diff_0 = d_diff_0 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[11,2] = mean(as.matrix(d_diff_0), na.rm=T)
n_diff_0 = length(d_diff_0[!is.na(d_diff_0)])
prop_male[11,3] = sd(as.matrix(d_diff_0), na.rm=T)/sqrt(n_diff_0)

d_diff_1 = d_diff_1 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[12,2] = mean(as.matrix(d_diff_1), na.rm=T)
n_diff_1 = length(d_diff_1[!is.na(d_diff_1)])
prop_male[12,3] = sd(as.matrix(d_diff_1), na.rm=T)/sqrt(n_diff_1)

d_diff_2 = d_diff_2 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[13,2] = mean(as.matrix(d_diff_2), na.rm=T)
n_diff_2 = length(d_diff_2[!is.na(d_diff_2)])
prop_male[13,3] = sd(as.matrix(d_diff_2), na.rm=T)/sqrt(n_diff_2)

d_diff_3 = d_diff_3 %>% 
  select(-c("condition", "standard_dev", "image_id"))
prop_male[14,2] = mean(as.matrix(d_diff_3), na.rm=T)
n_diff_3 = length(d_diff_3[!is.na(d_diff_3)])
prop_male[14,3] = sd(as.matrix(d_diff_3), na.rm=T)/sqrt(n_diff_3)

# plot proportion male values as scatter plot
plot <- ggplot(prop_male, aes(x=standard_dev, y=prop_male, color=condition)) +
  geom_point() +
  geom_smooth(method=glm, method.args = list(family="binomial"), se=FALSE) +
  geom_errorbar(aes(ymin = prop_male - standard_error, ymax = prop_male + standard_error), width=0.2) +
  xlab("Standard Deviation") +
  ylab("Proportion of Male Responses")

plot + scale_x_continuous(n.breaks = 7) + scale_y_continuous(n.breaks = 6)

```
The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
